name: lvm_presenter_remote
description: Control remoto de LVM Presenter en Windows.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ">=3.13.5 <3.14.0"
  flutter: ">=3.47.7 <3.48.0"

dependencies:
  flutter:
    sdk: flutter
  lvm_api:
    path: ../../packages/lvm_api
  lvm_design:
    path: ../../packages/lvm_design
  lvm_models:
    path: ../../packages/lvm_models
  lvm_persistence:
    path: ../../packages/lvm_persistence

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
