name: lvm_public
description: La Voz Misionera para congregantes y visitantes.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ">=3.13.5 <3.14.0"
  flutter: ">=3.47.7 <3.48.0"

dependencies:
  file_selector: 1.1.0
  flutter:
    sdk: flutter
  lvm_api:
    path: ../../packages/lvm_api
  lvm_design:
    path: ../../packages/lvm_design
  lvm_models:
    path: ../../packages/lvm_models
  lvm_persistence:
    path: ../../packages/lvm_persistence
  shared_preferences: 2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
